# Generated by Django 6.0.2 on 2026-03-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationapplication',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
