# Generated by Django 6.0.2 on 2026-02-28 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('ethiopia', 'Ethiopia'), ('kenya', 'Kenya'), ('rwanda', 'Rwanda'), ('uganda', 'Uganda'), ('other', 'Other')], max_length=32)),
                ('region', models.CharField(blank=True, choices=[('addis_ababa', 'Addis Ababa'), ('amhara', 'Amhara Region'), ('afar', 'Afar Region'), ('benishangul_gumuz', 'Benishangul-Gumuz'), ('central_ethiopia', 'Central Ethiopia'), ('dire_dawa', 'Dire Dawa'), ('gambela', 'Gambela'), ('harari', 'Harari'), ('oromia', 'Oromia'), ('sidama', 'Sidama'), ('somali', 'Somali'), ('south_ethiopia', 'South Ethiopia'), ('southwest_ethiopia', "Southwest Ethiopia People's Region"), ('tigray', 'Tigray')], max_length=64)),
                ('age_range', models.CharField(blank=True, choices=[('13_17', '13–17'), ('18_22', '18–22'), ('23_25', '23–25'), ('26_30', '26–30'), ('31_35', '31–35'), ('36_40', '36–40'), ('41_plus', '41 and Older')], max_length=16)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=32)),
                ('field_of_study', models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('arts', 'Arts'), ('business', 'Business'), ('cs_it', 'Computer science and IT'), ('education', 'Education'), ('engineering', 'Engineering'), ('humanities', 'Humanities'), ('law', 'Law'), ('medicine', 'Medicine'), ('natural_science', 'Natural science'), ('social_science', 'Social science'), ('other', 'Other')], max_length=32)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('employment_status', models.CharField(blank=True, choices=[('full_time', 'Full-time employee'), ('part_time', 'Part-time employee'), ('freelancer', 'Freelancer'), ('entrepreneur', 'Entrepreneur'), ('student', 'Student'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=32)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('unemployment_description', models.TextField(blank=True)),
                ('professional_experience', models.CharField(blank=True, choices=[('none', 'No professional experience'), ('lt_1', '<1 year'), ('1_2', '1–2 years'), ('2_3', '2–3 years'), ('3_5', '3–5 years'), ('5_6', '5–6 years'), ('6_10', '6–10 years'), ('10_plus', '10+ years')], max_length=16)),
                ('enrollment_motivation', models.CharField(blank=True, choices=[('new_job', 'Start a new job'), ('promotion', 'Get promotion or raise'), ('new_skill', 'Learn new skill'), ('advanced_degree', 'Prepare for advanced degree'), ('start_business', 'Start business'), ('interest', 'General interest'), ('internship', 'Internship preparation'), ('other', 'Other')], max_length=32)),
                ('referral_source', models.CharField(blank=True, choices=[('email', 'Email'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('telegram', 'Telegram'), ('search_engine', 'Search Engine'), ('sms', 'SMS'), ('website_search', 'Website search'), ('program_website', 'Program website'), ('friend_referral', 'Friend referral'), ('other', 'Other')], max_length=32)),
                ('is_information_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
    ]
