# Generated by Django 6.0.2 on 2026-02-28 22:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_article_deleted_at_article_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentProfileSnapshot',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nationality', models.CharField(blank=True, max_length=32)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('age_range', models.CharField(blank=True, max_length=16)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('education_level', models.CharField(blank=True, max_length=32)),
                ('field_of_study', models.CharField(blank=True, max_length=32)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('employment_status', models.CharField(blank=True, max_length=32)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('unemployment_description', models.TextField(blank=True)),
                ('professional_experience', models.CharField(blank=True, max_length=16)),
                ('enrollment_motivation', models.CharField(blank=True, max_length=32)),
                ('referral_source', models.CharField(blank=True, max_length=32)),
                ('is_information_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_snapshots', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_snapshot', to='courses.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
