# Generated by Django 6.0.2 on 2026-03-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assessmentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
