# Generated by Django 6.0.2 on 2026-03-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_certificate_exam_course_level'),
        ('courses', '0006_course_thumbnail_url'),
    ]

    operations = [
    ]
