# Generated by Django 6.0.3 on 2026-07-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20260327_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
